"""initial_migration_all_models

Revision ID: 30eac04d8270
Revises: 
Create Date: 2026-01-14 14:49:23.257180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30eac04d8270'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_api_calls', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('modules_enabled', sa.JSON(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('data_retention_days', sa.Integer(), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=50), nullable=True),
    sa.Column('address_zip', sa.String(length=20), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_cnpj'), 'tenants', ['cnpj'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('agendamentos',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('profissional', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('confirmado', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_centro_custo'), 'agendamentos', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_agendamentos_convenio'), 'agendamentos', ['convenio'], unique=False)
    op.create_index(op.f('ix_agendamentos_data'), 'agendamentos', ['data'], unique=False)
    op.create_index(op.f('ix_agendamentos_especialidade'), 'agendamentos', ['especialidade'], unique=False)
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_index(op.f('ix_agendamentos_paciente_id'), 'agendamentos', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_agendamentos_tenant_id'), 'agendamentos', ['tenant_id'], unique=False)
    op.create_table('ambulatorio_consultas',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('medico', sa.String(length=255), nullable=True),
    sa.Column('tipo_consulta', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('categoria_convenio', sa.String(length=20), nullable=False),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('queixa_principal', sa.String(length=500), nullable=True),
    sa.Column('diagnostico', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulatorio_consultas_centro_custo'), 'ambulatorio_consultas', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_ambulatorio_consultas_convenio'), 'ambulatorio_consultas', ['convenio'], unique=False)
    op.create_index(op.f('ix_ambulatorio_consultas_data'), 'ambulatorio_consultas', ['data'], unique=False)
    op.create_index(op.f('ix_ambulatorio_consultas_especialidade'), 'ambulatorio_consultas', ['especialidade'], unique=False)
    op.create_index(op.f('ix_ambulatorio_consultas_id'), 'ambulatorio_consultas', ['id'], unique=False)
    op.create_index(op.f('ix_ambulatorio_consultas_paciente_id'), 'ambulatorio_consultas', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_ambulatorio_consultas_tenant_id'), 'ambulatorio_consultas', ['tenant_id'], unique=False)
    op.create_table('atendimentos',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=False),
    sa.Column('categoria_convenio', sa.String(length=20), nullable=False),
    sa.Column('profissional', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tempo_espera_minutos', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('faixa_etaria', sa.String(length=20), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_centro_custo'), 'atendimentos', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_atendimentos_convenio'), 'atendimentos', ['convenio'], unique=False)
    op.create_index(op.f('ix_atendimentos_data'), 'atendimentos', ['data'], unique=False)
    op.create_index(op.f('ix_atendimentos_especialidade'), 'atendimentos', ['especialidade'], unique=False)
    op.create_index(op.f('ix_atendimentos_id'), 'atendimentos', ['id'], unique=False)
    op.create_index(op.f('ix_atendimentos_paciente_id'), 'atendimentos', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_atendimentos_tenant_id'), 'atendimentos', ['tenant_id'], unique=False)
    op.create_table('atividades_spp',
    sa.Column('tipo_atividade', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('responsavel', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('participantes', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atividades_spp_centro_custo'), 'atividades_spp', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_atividades_spp_data'), 'atividades_spp', ['data'], unique=False)
    op.create_index(op.f('ix_atividades_spp_id'), 'atividades_spp', ['id'], unique=False)
    op.create_index(op.f('ix_atividades_spp_setor'), 'atividades_spp', ['setor'], unique=False)
    op.create_index(op.f('ix_atividades_spp_tenant_id'), 'atividades_spp', ['tenant_id'], unique=False)
    op.create_table('avaliacoes_nutricionais',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('tipo_avaliacao', sa.String(length=50), nullable=False),
    sa.Column('imc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('altura', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('diagnostico', sa.String(length=100), nullable=True),
    sa.Column('dieta', sa.String(length=100), nullable=True),
    sa.Column('profissional', sa.String(length=255), nullable=False),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_nutricionais_centro_custo'), 'avaliacoes_nutricionais', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_avaliacoes_nutricionais_data'), 'avaliacoes_nutricionais', ['data'], unique=False)
    op.create_index(op.f('ix_avaliacoes_nutricionais_id'), 'avaliacoes_nutricionais', ['id'], unique=False)
    op.create_index(op.f('ix_avaliacoes_nutricionais_paciente_id'), 'avaliacoes_nutricionais', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_avaliacoes_nutricionais_tenant_id'), 'avaliacoes_nutricionais', ['tenant_id'], unique=False)
    op.create_table('chamados_ti',
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('solicitante', sa.String(length=255), nullable=False),
    sa.Column('data_abertura', sa.String(), nullable=False),
    sa.Column('data_fechamento', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tecnico_responsavel', sa.String(length=255), nullable=True),
    sa.Column('solucao', sa.String(length=1000), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamados_ti_centro_custo'), 'chamados_ti', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_chamados_ti_data_abertura'), 'chamados_ti', ['data_abertura'], unique=False)
    op.create_index(op.f('ix_chamados_ti_id'), 'chamados_ti', ['id'], unique=False)
    op.create_index(op.f('ix_chamados_ti_setor'), 'chamados_ti', ['setor'], unique=False)
    op.create_index(op.f('ix_chamados_ti_tenant_id'), 'chamados_ti', ['tenant_id'], unique=False)
    op.create_table('exames_imagem',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data_solicitacao', sa.String(), nullable=False),
    sa.Column('data_realizacao', sa.String(), nullable=True),
    sa.Column('tipo_exame', sa.String(length=100), nullable=False),
    sa.Column('modalidade', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('laudo', sa.String(), nullable=True),
    sa.Column('medico_solicitante', sa.String(length=255), nullable=True),
    sa.Column('medico_laudador', sa.String(length=255), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_imagem_centro_custo'), 'exames_imagem', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_exames_imagem_convenio'), 'exames_imagem', ['convenio'], unique=False)
    op.create_index(op.f('ix_exames_imagem_data_solicitacao'), 'exames_imagem', ['data_solicitacao'], unique=False)
    op.create_index(op.f('ix_exames_imagem_id'), 'exames_imagem', ['id'], unique=False)
    op.create_index(op.f('ix_exames_imagem_paciente_id'), 'exames_imagem', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_exames_imagem_tenant_id'), 'exames_imagem', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_exames_imagem_tipo_exame'), 'exames_imagem', ['tipo_exame'], unique=False)
    op.create_table('exames_laboratoriais',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data_solicitacao', sa.String(), nullable=False),
    sa.Column('data_coleta', sa.String(), nullable=True),
    sa.Column('data_resultado', sa.String(), nullable=True),
    sa.Column('tipo_exame', sa.String(length=100), nullable=False),
    sa.Column('codigo_exame', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('valor_referencia', sa.String(), nullable=True),
    sa.Column('medico_solicitante', sa.String(length=255), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_laboratoriais_centro_custo'), 'exames_laboratoriais', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_exames_laboratoriais_convenio'), 'exames_laboratoriais', ['convenio'], unique=False)
    op.create_index(op.f('ix_exames_laboratoriais_data_solicitacao'), 'exames_laboratoriais', ['data_solicitacao'], unique=False)
    op.create_index(op.f('ix_exames_laboratoriais_id'), 'exames_laboratoriais', ['id'], unique=False)
    op.create_index(op.f('ix_exames_laboratoriais_paciente_id'), 'exames_laboratoriais', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_exames_laboratoriais_tenant_id'), 'exames_laboratoriais', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_exames_laboratoriais_tipo_exame'), 'exames_laboratoriais', ['tipo_exame'], unique=False)
    op.create_table('faturamentos',
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('paciente_nome', sa.String(length=255), nullable=True),
    sa.Column('data_faturamento', sa.String(), nullable=False),
    sa.Column('tipo_faturamento', sa.String(length=50), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('categoria_convenio', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_glosado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_recebido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_recebimento', sa.String(), nullable=True),
    sa.Column('numero_guia', sa.String(length=100), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faturamentos_centro_custo'), 'faturamentos', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_faturamentos_convenio'), 'faturamentos', ['convenio'], unique=False)
    op.create_index(op.f('ix_faturamentos_data_faturamento'), 'faturamentos', ['data_faturamento'], unique=False)
    op.create_index(op.f('ix_faturamentos_id'), 'faturamentos', ['id'], unique=False)
    op.create_index(op.f('ix_faturamentos_paciente_id'), 'faturamentos', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_faturamentos_tenant_id'), 'faturamentos', ['tenant_id'], unique=False)
    op.create_table('infeccoes',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data_diagnostico', sa.String(), nullable=False),
    sa.Column('tipo_infeccao', sa.String(length=100), nullable=False),
    sa.Column('topografia', sa.String(length=100), nullable=False),
    sa.Column('agente', sa.String(length=255), nullable=True),
    sa.Column('antibiotico', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('classificacao', sa.String(length=50), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infeccoes_centro_custo'), 'infeccoes', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_infeccoes_data_diagnostico'), 'infeccoes', ['data_diagnostico'], unique=False)
    op.create_index(op.f('ix_infeccoes_id'), 'infeccoes', ['id'], unique=False)
    op.create_index(op.f('ix_infeccoes_paciente_id'), 'infeccoes', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_infeccoes_setor'), 'infeccoes', ['setor'], unique=False)
    op.create_index(op.f('ix_infeccoes_tenant_id'), 'infeccoes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_infeccoes_tipo_infeccao'), 'infeccoes', ['tipo_infeccao'], unique=False)
    op.create_table('integracoes',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('config', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integracoes_id'), 'integracoes', ['id'], unique=False)
    op.create_index(op.f('ix_integracoes_tenant_id'), 'integracoes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_integracoes_tipo'), 'integracoes', ['tipo'], unique=False)
    op.create_table('itens_estoque',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('quantidade_minima', sa.Integer(), nullable=False),
    sa.Column('quantidade_maxima', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fornecedor', sa.String(length=255), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_estoque_categoria'), 'itens_estoque', ['categoria'], unique=False)
    op.create_index(op.f('ix_itens_estoque_centro_custo'), 'itens_estoque', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_itens_estoque_codigo'), 'itens_estoque', ['codigo'], unique=True)
    op.create_index(op.f('ix_itens_estoque_id'), 'itens_estoque', ['id'], unique=False)
    op.create_index(op.f('ix_itens_estoque_tenant_id'), 'itens_estoque', ['tenant_id'], unique=False)
    op.create_table('leitos',
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('paciente_nome', sa.String(length=255), nullable=True),
    sa.Column('data_ocupacao', sa.String(), nullable=True),
    sa.Column('data_liberacao', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leitos_centro_custo'), 'leitos', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_leitos_id'), 'leitos', ['id'], unique=False)
    op.create_index(op.f('ix_leitos_numero'), 'leitos', ['numero'], unique=False)
    op.create_index(op.f('ix_leitos_paciente_id'), 'leitos', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_leitos_tenant_id'), 'leitos', ['tenant_id'], unique=False)
    op.create_table('modulos_config',
    sa.Column('modulo_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulos_config_id'), 'modulos_config', ['id'], unique=False)
    op.create_index(op.f('ix_modulos_config_modulo_id'), 'modulos_config', ['modulo_id'], unique=True)
    op.create_index(op.f('ix_modulos_config_tenant_id'), 'modulos_config', ['tenant_id'], unique=False)
    op.create_table('movimentacoes_financeiras',
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('fornecedor', sa.String(length=255), nullable=True),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_financeiras_categoria'), 'movimentacoes_financeiras', ['categoria'], unique=False)
    op.create_index(op.f('ix_movimentacoes_financeiras_centro_custo'), 'movimentacoes_financeiras', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_movimentacoes_financeiras_data'), 'movimentacoes_financeiras', ['data'], unique=False)
    op.create_index(op.f('ix_movimentacoes_financeiras_id'), 'movimentacoes_financeiras', ['id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_financeiras_tenant_id'), 'movimentacoes_financeiras', ['tenant_id'], unique=False)
    op.create_table('notificacoes_config',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_kpis_diarios', sa.Boolean(), nullable=False),
    sa.Column('email_alertas', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_alertas_criticos', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_alertas_criticos', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_config_id'), 'notificacoes_config', ['id'], unique=False)
    op.create_index(op.f('ix_notificacoes_config_tenant_id'), 'notificacoes_config', ['tenant_id'], unique=True)
    op.create_table('ocorrencias_sesmt',
    sa.Column('tipo_ocorrencia', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('funcionario', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('gravidade', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('medidas_tomadas', sa.String(length=1000), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocorrencias_sesmt_centro_custo'), 'ocorrencias_sesmt', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_ocorrencias_sesmt_data'), 'ocorrencias_sesmt', ['data'], unique=False)
    op.create_index(op.f('ix_ocorrencias_sesmt_id'), 'ocorrencias_sesmt', ['id'], unique=False)
    op.create_index(op.f('ix_ocorrencias_sesmt_setor'), 'ocorrencias_sesmt', ['setor'], unique=False)
    op.create_index(op.f('ix_ocorrencias_sesmt_tenant_id'), 'ocorrencias_sesmt', ['tenant_id'], unique=False)
    op.create_table('prescricoes',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data_prescricao', sa.String(), nullable=False),
    sa.Column('medicamento', sa.String(length=255), nullable=False),
    sa.Column('principio_ativo', sa.String(length=255), nullable=True),
    sa.Column('dosagem', sa.String(length=100), nullable=False),
    sa.Column('via', sa.String(length=50), nullable=False),
    sa.Column('frequencia', sa.String(length=100), nullable=True),
    sa.Column('duracao', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dispensado', sa.Boolean(), nullable=False),
    sa.Column('data_dispensacao', sa.String(), nullable=True),
    sa.Column('medico_prescritor', sa.String(length=255), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescricoes_centro_custo'), 'prescricoes', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_prescricoes_data_prescricao'), 'prescricoes', ['data_prescricao'], unique=False)
    op.create_index(op.f('ix_prescricoes_id'), 'prescricoes', ['id'], unique=False)
    op.create_index(op.f('ix_prescricoes_paciente_id'), 'prescricoes', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_prescricoes_tenant_id'), 'prescricoes', ['tenant_id'], unique=False)
    op.create_table('refeicoes_gerenciais',
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('tipo_refeicao', sa.String(length=50), nullable=False),
    sa.Column('quantidade_refeicoes', sa.Integer(), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('cardapio', sa.String(length=500), nullable=True),
    sa.Column('fornecedor', sa.String(length=255), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refeicoes_gerenciais_centro_custo'), 'refeicoes_gerenciais', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_refeicoes_gerenciais_data'), 'refeicoes_gerenciais', ['data'], unique=False)
    op.create_index(op.f('ix_refeicoes_gerenciais_id'), 'refeicoes_gerenciais', ['id'], unique=False)
    op.create_index(op.f('ix_refeicoes_gerenciais_setor'), 'refeicoes_gerenciais', ['setor'], unique=False)
    op.create_index(op.f('ix_refeicoes_gerenciais_tenant_id'), 'refeicoes_gerenciais', ['tenant_id'], unique=False)
    op.create_table('seguranca_config',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=False),
    sa.Column('password_require_uppercase', sa.Boolean(), nullable=False),
    sa.Column('password_require_lowercase', sa.Boolean(), nullable=False),
    sa.Column('password_require_numbers', sa.Boolean(), nullable=False),
    sa.Column('password_require_special', sa.Boolean(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_login_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seguranca_config_id'), 'seguranca_config', ['id'], unique=False)
    op.create_index(op.f('ix_seguranca_config_tenant_id'), 'seguranca_config', ['tenant_id'], unique=True)
    op.create_table('servicos_higienizacao',
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('tipo_servico', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('profissional', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_higienizacao_centro_custo'), 'servicos_higienizacao', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_servicos_higienizacao_data'), 'servicos_higienizacao', ['data'], unique=False)
    op.create_index(op.f('ix_servicos_higienizacao_id'), 'servicos_higienizacao', ['id'], unique=False)
    op.create_index(op.f('ix_servicos_higienizacao_setor'), 'servicos_higienizacao', ['setor'], unique=False)
    op.create_index(op.f('ix_servicos_higienizacao_tenant_id'), 'servicos_higienizacao', ['tenant_id'], unique=False)
    op.create_table('servicos_hotelaria',
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('tipo_servico', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('profissional', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_hotelaria_centro_custo'), 'servicos_hotelaria', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_servicos_hotelaria_data'), 'servicos_hotelaria', ['data'], unique=False)
    op.create_index(op.f('ix_servicos_hotelaria_id'), 'servicos_hotelaria', ['id'], unique=False)
    op.create_index(op.f('ix_servicos_hotelaria_setor'), 'servicos_hotelaria', ['setor'], unique=False)
    op.create_index(op.f('ix_servicos_hotelaria_tenant_id'), 'servicos_hotelaria', ['tenant_id'], unique=False)
    op.create_table('servicos_lavanderia',
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('tipo_roupa', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.String(), nullable=False),
    sa.Column('data_saida', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('profissional', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_lavanderia_centro_custo'), 'servicos_lavanderia', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_servicos_lavanderia_data_entrada'), 'servicos_lavanderia', ['data_entrada'], unique=False)
    op.create_index(op.f('ix_servicos_lavanderia_id'), 'servicos_lavanderia', ['id'], unique=False)
    op.create_index(op.f('ix_servicos_lavanderia_setor'), 'servicos_lavanderia', ['setor'], unique=False)
    op.create_index(op.f('ix_servicos_lavanderia_tenant_id'), 'servicos_lavanderia', ['tenant_id'], unique=False)
    op.create_table('sessoes_fisioterapia',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('tipo_sessao', sa.String(length=100), nullable=False),
    sa.Column('profissional', sa.String(length=255), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evolucao', sa.String(length=1000), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_fisioterapia_centro_custo'), 'sessoes_fisioterapia', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_sessoes_fisioterapia_data'), 'sessoes_fisioterapia', ['data'], unique=False)
    op.create_index(op.f('ix_sessoes_fisioterapia_id'), 'sessoes_fisioterapia', ['id'], unique=False)
    op.create_index(op.f('ix_sessoes_fisioterapia_paciente_id'), 'sessoes_fisioterapia', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_sessoes_fisioterapia_tenant_id'), 'sessoes_fisioterapia', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.String(), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('transfusoes',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.Column('tipo_sangue', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('hemocomponente', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reacao', sa.String(length=50), nullable=True),
    sa.Column('medico_solicitante', sa.String(length=255), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfusoes_centro_custo'), 'transfusoes', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_transfusoes_data'), 'transfusoes', ['data'], unique=False)
    op.create_index(op.f('ix_transfusoes_id'), 'transfusoes', ['id'], unique=False)
    op.create_index(op.f('ix_transfusoes_paciente_id'), 'transfusoes', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_transfusoes_tenant_id'), 'transfusoes', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('uti_internacoes',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data_entrada', sa.String(), nullable=False),
    sa.Column('data_saida', sa.String(), nullable=True),
    sa.Column('apache_score', sa.Integer(), nullable=True),
    sa.Column('ventilacao', sa.Boolean(), nullable=False),
    sa.Column('dias_ventilacao', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('obito', sa.Boolean(), nullable=False),
    sa.Column('dias_permanencia', sa.Integer(), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('medico', sa.String(length=255), nullable=True),
    sa.Column('diagnostico', sa.String(length=500), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uti_internacoes_centro_custo'), 'uti_internacoes', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_uti_internacoes_data_entrada'), 'uti_internacoes', ['data_entrada'], unique=False)
    op.create_index(op.f('ix_uti_internacoes_especialidade'), 'uti_internacoes', ['especialidade'], unique=False)
    op.create_index(op.f('ix_uti_internacoes_id'), 'uti_internacoes', ['id'], unique=False)
    op.create_index(op.f('ix_uti_internacoes_paciente_id'), 'uti_internacoes', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_uti_internacoes_tenant_id'), 'uti_internacoes', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('internacoes',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=255), nullable=False),
    sa.Column('data_entrada', sa.String(), nullable=False),
    sa.Column('data_saida', sa.String(), nullable=True),
    sa.Column('leito_id', sa.UUID(), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=False),
    sa.Column('medico', sa.String(length=255), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('diagnostico', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('classificacao_risco', sa.String(length=20), nullable=True),
    sa.Column('proveniencia', sa.String(length=100), nullable=True),
    sa.Column('vinculado_ps', sa.Boolean(), nullable=False),
    sa.Column('obito', sa.Boolean(), nullable=False),
    sa.Column('dias_permanencia', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leito_id'], ['leitos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internacoes_centro_custo'), 'internacoes', ['centro_custo'], unique=False)
    op.create_index(op.f('ix_internacoes_convenio'), 'internacoes', ['convenio'], unique=False)
    op.create_index(op.f('ix_internacoes_data_entrada'), 'internacoes', ['data_entrada'], unique=False)
    op.create_index(op.f('ix_internacoes_especialidade'), 'internacoes', ['especialidade'], unique=False)
    op.create_index(op.f('ix_internacoes_id'), 'internacoes', ['id'], unique=False)
    op.create_index(op.f('ix_internacoes_leito_id'), 'internacoes', ['leito_id'], unique=False)
    op.create_index(op.f('ix_internacoes_paciente_id'), 'internacoes', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_internacoes_tenant_id'), 'internacoes', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=True)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_internacoes_tenant_id'), table_name='internacoes')
    op.drop_index(op.f('ix_internacoes_paciente_id'), table_name='internacoes')
    op.drop_index(op.f('ix_internacoes_leito_id'), table_name='internacoes')
    op.drop_index(op.f('ix_internacoes_id'), table_name='internacoes')
    op.drop_index(op.f('ix_internacoes_especialidade'), table_name='internacoes')
    op.drop_index(op.f('ix_internacoes_data_entrada'), table_name='internacoes')
    op.drop_index(op.f('ix_internacoes_convenio'), table_name='internacoes')
    op.drop_index(op.f('ix_internacoes_centro_custo'), table_name='internacoes')
    op.drop_table('internacoes')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_uti_internacoes_tenant_id'), table_name='uti_internacoes')
    op.drop_index(op.f('ix_uti_internacoes_paciente_id'), table_name='uti_internacoes')
    op.drop_index(op.f('ix_uti_internacoes_id'), table_name='uti_internacoes')
    op.drop_index(op.f('ix_uti_internacoes_especialidade'), table_name='uti_internacoes')
    op.drop_index(op.f('ix_uti_internacoes_data_entrada'), table_name='uti_internacoes')
    op.drop_index(op.f('ix_uti_internacoes_centro_custo'), table_name='uti_internacoes')
    op.drop_table('uti_internacoes')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transfusoes_tenant_id'), table_name='transfusoes')
    op.drop_index(op.f('ix_transfusoes_paciente_id'), table_name='transfusoes')
    op.drop_index(op.f('ix_transfusoes_id'), table_name='transfusoes')
    op.drop_index(op.f('ix_transfusoes_data'), table_name='transfusoes')
    op.drop_index(op.f('ix_transfusoes_centro_custo'), table_name='transfusoes')
    op.drop_table('transfusoes')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sessoes_fisioterapia_tenant_id'), table_name='sessoes_fisioterapia')
    op.drop_index(op.f('ix_sessoes_fisioterapia_paciente_id'), table_name='sessoes_fisioterapia')
    op.drop_index(op.f('ix_sessoes_fisioterapia_id'), table_name='sessoes_fisioterapia')
    op.drop_index(op.f('ix_sessoes_fisioterapia_data'), table_name='sessoes_fisioterapia')
    op.drop_index(op.f('ix_sessoes_fisioterapia_centro_custo'), table_name='sessoes_fisioterapia')
    op.drop_table('sessoes_fisioterapia')
    op.drop_index(op.f('ix_servicos_lavanderia_tenant_id'), table_name='servicos_lavanderia')
    op.drop_index(op.f('ix_servicos_lavanderia_setor'), table_name='servicos_lavanderia')
    op.drop_index(op.f('ix_servicos_lavanderia_id'), table_name='servicos_lavanderia')
    op.drop_index(op.f('ix_servicos_lavanderia_data_entrada'), table_name='servicos_lavanderia')
    op.drop_index(op.f('ix_servicos_lavanderia_centro_custo'), table_name='servicos_lavanderia')
    op.drop_table('servicos_lavanderia')
    op.drop_index(op.f('ix_servicos_hotelaria_tenant_id'), table_name='servicos_hotelaria')
    op.drop_index(op.f('ix_servicos_hotelaria_setor'), table_name='servicos_hotelaria')
    op.drop_index(op.f('ix_servicos_hotelaria_id'), table_name='servicos_hotelaria')
    op.drop_index(op.f('ix_servicos_hotelaria_data'), table_name='servicos_hotelaria')
    op.drop_index(op.f('ix_servicos_hotelaria_centro_custo'), table_name='servicos_hotelaria')
    op.drop_table('servicos_hotelaria')
    op.drop_index(op.f('ix_servicos_higienizacao_tenant_id'), table_name='servicos_higienizacao')
    op.drop_index(op.f('ix_servicos_higienizacao_setor'), table_name='servicos_higienizacao')
    op.drop_index(op.f('ix_servicos_higienizacao_id'), table_name='servicos_higienizacao')
    op.drop_index(op.f('ix_servicos_higienizacao_data'), table_name='servicos_higienizacao')
    op.drop_index(op.f('ix_servicos_higienizacao_centro_custo'), table_name='servicos_higienizacao')
    op.drop_table('servicos_higienizacao')
    op.drop_index(op.f('ix_seguranca_config_tenant_id'), table_name='seguranca_config')
    op.drop_index(op.f('ix_seguranca_config_id'), table_name='seguranca_config')
    op.drop_table('seguranca_config')
    op.drop_index(op.f('ix_refeicoes_gerenciais_tenant_id'), table_name='refeicoes_gerenciais')
    op.drop_index(op.f('ix_refeicoes_gerenciais_setor'), table_name='refeicoes_gerenciais')
    op.drop_index(op.f('ix_refeicoes_gerenciais_id'), table_name='refeicoes_gerenciais')
    op.drop_index(op.f('ix_refeicoes_gerenciais_data'), table_name='refeicoes_gerenciais')
    op.drop_index(op.f('ix_refeicoes_gerenciais_centro_custo'), table_name='refeicoes_gerenciais')
    op.drop_table('refeicoes_gerenciais')
    op.drop_index(op.f('ix_prescricoes_tenant_id'), table_name='prescricoes')
    op.drop_index(op.f('ix_prescricoes_paciente_id'), table_name='prescricoes')
    op.drop_index(op.f('ix_prescricoes_id'), table_name='prescricoes')
    op.drop_index(op.f('ix_prescricoes_data_prescricao'), table_name='prescricoes')
    op.drop_index(op.f('ix_prescricoes_centro_custo'), table_name='prescricoes')
    op.drop_table('prescricoes')
    op.drop_index(op.f('ix_ocorrencias_sesmt_tenant_id'), table_name='ocorrencias_sesmt')
    op.drop_index(op.f('ix_ocorrencias_sesmt_setor'), table_name='ocorrencias_sesmt')
    op.drop_index(op.f('ix_ocorrencias_sesmt_id'), table_name='ocorrencias_sesmt')
    op.drop_index(op.f('ix_ocorrencias_sesmt_data'), table_name='ocorrencias_sesmt')
    op.drop_index(op.f('ix_ocorrencias_sesmt_centro_custo'), table_name='ocorrencias_sesmt')
    op.drop_table('ocorrencias_sesmt')
    op.drop_index(op.f('ix_notificacoes_config_tenant_id'), table_name='notificacoes_config')
    op.drop_index(op.f('ix_notificacoes_config_id'), table_name='notificacoes_config')
    op.drop_table('notificacoes_config')
    op.drop_index(op.f('ix_movimentacoes_financeiras_tenant_id'), table_name='movimentacoes_financeiras')
    op.drop_index(op.f('ix_movimentacoes_financeiras_id'), table_name='movimentacoes_financeiras')
    op.drop_index(op.f('ix_movimentacoes_financeiras_data'), table_name='movimentacoes_financeiras')
    op.drop_index(op.f('ix_movimentacoes_financeiras_centro_custo'), table_name='movimentacoes_financeiras')
    op.drop_index(op.f('ix_movimentacoes_financeiras_categoria'), table_name='movimentacoes_financeiras')
    op.drop_table('movimentacoes_financeiras')
    op.drop_index(op.f('ix_modulos_config_tenant_id'), table_name='modulos_config')
    op.drop_index(op.f('ix_modulos_config_modulo_id'), table_name='modulos_config')
    op.drop_index(op.f('ix_modulos_config_id'), table_name='modulos_config')
    op.drop_table('modulos_config')
    op.drop_index(op.f('ix_leitos_tenant_id'), table_name='leitos')
    op.drop_index(op.f('ix_leitos_paciente_id'), table_name='leitos')
    op.drop_index(op.f('ix_leitos_numero'), table_name='leitos')
    op.drop_index(op.f('ix_leitos_id'), table_name='leitos')
    op.drop_index(op.f('ix_leitos_centro_custo'), table_name='leitos')
    op.drop_table('leitos')
    op.drop_index(op.f('ix_itens_estoque_tenant_id'), table_name='itens_estoque')
    op.drop_index(op.f('ix_itens_estoque_id'), table_name='itens_estoque')
    op.drop_index(op.f('ix_itens_estoque_codigo'), table_name='itens_estoque')
    op.drop_index(op.f('ix_itens_estoque_centro_custo'), table_name='itens_estoque')
    op.drop_index(op.f('ix_itens_estoque_categoria'), table_name='itens_estoque')
    op.drop_table('itens_estoque')
    op.drop_index(op.f('ix_integracoes_tipo'), table_name='integracoes')
    op.drop_index(op.f('ix_integracoes_tenant_id'), table_name='integracoes')
    op.drop_index(op.f('ix_integracoes_id'), table_name='integracoes')
    op.drop_table('integracoes')
    op.drop_index(op.f('ix_infeccoes_tipo_infeccao'), table_name='infeccoes')
    op.drop_index(op.f('ix_infeccoes_tenant_id'), table_name='infeccoes')
    op.drop_index(op.f('ix_infeccoes_setor'), table_name='infeccoes')
    op.drop_index(op.f('ix_infeccoes_paciente_id'), table_name='infeccoes')
    op.drop_index(op.f('ix_infeccoes_id'), table_name='infeccoes')
    op.drop_index(op.f('ix_infeccoes_data_diagnostico'), table_name='infeccoes')
    op.drop_index(op.f('ix_infeccoes_centro_custo'), table_name='infeccoes')
    op.drop_table('infeccoes')
    op.drop_index(op.f('ix_faturamentos_tenant_id'), table_name='faturamentos')
    op.drop_index(op.f('ix_faturamentos_paciente_id'), table_name='faturamentos')
    op.drop_index(op.f('ix_faturamentos_id'), table_name='faturamentos')
    op.drop_index(op.f('ix_faturamentos_data_faturamento'), table_name='faturamentos')
    op.drop_index(op.f('ix_faturamentos_convenio'), table_name='faturamentos')
    op.drop_index(op.f('ix_faturamentos_centro_custo'), table_name='faturamentos')
    op.drop_table('faturamentos')
    op.drop_index(op.f('ix_exames_laboratoriais_tipo_exame'), table_name='exames_laboratoriais')
    op.drop_index(op.f('ix_exames_laboratoriais_tenant_id'), table_name='exames_laboratoriais')
    op.drop_index(op.f('ix_exames_laboratoriais_paciente_id'), table_name='exames_laboratoriais')
    op.drop_index(op.f('ix_exames_laboratoriais_id'), table_name='exames_laboratoriais')
    op.drop_index(op.f('ix_exames_laboratoriais_data_solicitacao'), table_name='exames_laboratoriais')
    op.drop_index(op.f('ix_exames_laboratoriais_convenio'), table_name='exames_laboratoriais')
    op.drop_index(op.f('ix_exames_laboratoriais_centro_custo'), table_name='exames_laboratoriais')
    op.drop_table('exames_laboratoriais')
    op.drop_index(op.f('ix_exames_imagem_tipo_exame'), table_name='exames_imagem')
    op.drop_index(op.f('ix_exames_imagem_tenant_id'), table_name='exames_imagem')
    op.drop_index(op.f('ix_exames_imagem_paciente_id'), table_name='exames_imagem')
    op.drop_index(op.f('ix_exames_imagem_id'), table_name='exames_imagem')
    op.drop_index(op.f('ix_exames_imagem_data_solicitacao'), table_name='exames_imagem')
    op.drop_index(op.f('ix_exames_imagem_convenio'), table_name='exames_imagem')
    op.drop_index(op.f('ix_exames_imagem_centro_custo'), table_name='exames_imagem')
    op.drop_table('exames_imagem')
    op.drop_index(op.f('ix_chamados_ti_tenant_id'), table_name='chamados_ti')
    op.drop_index(op.f('ix_chamados_ti_setor'), table_name='chamados_ti')
    op.drop_index(op.f('ix_chamados_ti_id'), table_name='chamados_ti')
    op.drop_index(op.f('ix_chamados_ti_data_abertura'), table_name='chamados_ti')
    op.drop_index(op.f('ix_chamados_ti_centro_custo'), table_name='chamados_ti')
    op.drop_table('chamados_ti')
    op.drop_index(op.f('ix_avaliacoes_nutricionais_tenant_id'), table_name='avaliacoes_nutricionais')
    op.drop_index(op.f('ix_avaliacoes_nutricionais_paciente_id'), table_name='avaliacoes_nutricionais')
    op.drop_index(op.f('ix_avaliacoes_nutricionais_id'), table_name='avaliacoes_nutricionais')
    op.drop_index(op.f('ix_avaliacoes_nutricionais_data'), table_name='avaliacoes_nutricionais')
    op.drop_index(op.f('ix_avaliacoes_nutricionais_centro_custo'), table_name='avaliacoes_nutricionais')
    op.drop_table('avaliacoes_nutricionais')
    op.drop_index(op.f('ix_atividades_spp_tenant_id'), table_name='atividades_spp')
    op.drop_index(op.f('ix_atividades_spp_setor'), table_name='atividades_spp')
    op.drop_index(op.f('ix_atividades_spp_id'), table_name='atividades_spp')
    op.drop_index(op.f('ix_atividades_spp_data'), table_name='atividades_spp')
    op.drop_index(op.f('ix_atividades_spp_centro_custo'), table_name='atividades_spp')
    op.drop_table('atividades_spp')
    op.drop_index(op.f('ix_atendimentos_tenant_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_paciente_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_especialidade'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_data'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_convenio'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_centro_custo'), table_name='atendimentos')
    op.drop_table('atendimentos')
    op.drop_index(op.f('ix_ambulatorio_consultas_tenant_id'), table_name='ambulatorio_consultas')
    op.drop_index(op.f('ix_ambulatorio_consultas_paciente_id'), table_name='ambulatorio_consultas')
    op.drop_index(op.f('ix_ambulatorio_consultas_id'), table_name='ambulatorio_consultas')
    op.drop_index(op.f('ix_ambulatorio_consultas_especialidade'), table_name='ambulatorio_consultas')
    op.drop_index(op.f('ix_ambulatorio_consultas_data'), table_name='ambulatorio_consultas')
    op.drop_index(op.f('ix_ambulatorio_consultas_convenio'), table_name='ambulatorio_consultas')
    op.drop_index(op.f('ix_ambulatorio_consultas_centro_custo'), table_name='ambulatorio_consultas')
    op.drop_table('ambulatorio_consultas')
    op.drop_index(op.f('ix_agendamentos_tenant_id'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_paciente_id'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_especialidade'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_data'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_convenio'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_centro_custo'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_cnpj'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
