import {
  LayoutDashboard,
  Stethoscope,
  Building2,
  Settings,
  Calendar,
  FlaskConical,
  Pill,
  Activity,
  FileText,
  Wallet,
  Package,
  Users,
  ShieldCheck,
  HeartPulse,
  ClipboardList,
  BedDouble,
  UtensilsCrossed,
  Dumbbell,
  Scan,
  Droplet,
  Hospital,
  HardHat,
  Sparkles,
  Shirt,
  Monitor,
} from 'lucide-react';
import { NavSection } from '@/types/navigation';

export const navigationConfig: NavSection[] = [
  {
    label: 'Dashboard',
    icon: LayoutDashboard,
    path: '/',
  },
  {
    label: 'Assistencial',
    icon: Stethoscope,
    submenu: [
      {
        label: 'Atendimentos',
        path: '/assistencial/atendimentos',
        icon: Users,
        description: 'Análise tempo real',
      },
      {
        label: 'Ambulatório',
        path: '/assistencial/ambulatorio',
        icon: Hospital,
        description: 'Gestão ambulatorial',
      },
      {
        label: 'Agendas',
        path: '/assistencial/agendas',
        icon: Calendar,
        description: 'Agendamentos',
      },
      {
        label: 'Agência Transfusional',
        path: '/assistencial/agencia-transfusional',
        icon: Droplet,
        description: 'Controle de sangue',
      },
      {
        label: 'CCIH',
        path: '/assistencial/ccih',
        icon: ShieldCheck,
        description: 'Controle Infecção',
      },
      {
        label: 'Exames de Imagem',
        path: '/assistencial/exames-imagem',
        icon: Scan,
        description: 'Gestão de exames',
      },
      {
        label: 'Exames Laboratoriais',
        path: '/assistencial/exames-lab',
        icon: FlaskConical,
      },
      {
        label: 'Farmácia',
        path: '/assistencial/farmacia',
        icon: Pill,
      },
      {
        label: 'Fisioterapia',
        path: '/assistencial/fisioterapia',
        icon: Dumbbell,
        description: 'Análise de sessões',
      },
      {
        label: 'Internação',
        path: '/assistencial/internacao',
        icon: BedDouble,
        description: 'Gestão de leitos',
      },
      {
        label: 'Nutrição',
        path: '/assistencial/nutricao',
        icon: UtensilsCrossed,
        description: 'Gestão nutricional',
      },
      {
        label: 'UTI',
        path: '/assistencial/uti',
        icon: HeartPulse,
      },
    ],
  },
  {
    label: 'Gerencial',
    icon: Building2,
    submenu: [
      {
        label: 'Estoque',
        path: '/gerencial/estoque',
        icon: Package,
      },
      {
        label: 'Faturamento',
        path: '/gerencial/faturamento',
        icon: FileText,
      },
      {
        label: 'Financeiro',
        path: '/gerencial/financeiro',
        icon: Wallet,
      },
      {
        label: 'Higienização',
        path: '/gerencial/higienizacao',
        icon: Sparkles,
        description: 'Gestão de limpeza',
      },
      {
        label: 'Lavanderia',
        path: '/gerencial/lavanderia',
        icon: Shirt,
        description: 'Gestão de roupas',
      },
      {
        label: 'Relatórios',
        path: '/gerencial/relatorios',
        icon: ClipboardList,
      },
      {
        label: 'SESMT',
        path: '/gerencial/sesmt',
        icon: HardHat,
        description: 'Segurança do Trabalho',
      },
      {
        label: 'TI',
        path: '/gerencial/ti',
        icon: Monitor,
        description: 'Tecnologia da Informação',
      },
    ],
  },
  {
    label: 'Configurações',
    icon: Settings,
    path: '/configuracoes',
  },
];
